# Generated by Django 2.2.5 on 2019-12-04 03:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('icon', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
                ('title', models.CharField(default='', max_length=100)),
                ('artist', models.CharField(default='', max_length=100)),
                ('image', models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('lyrics', models.FileField(default='_default_lyrics.txt', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezonate.Genre')),
            ],
            options={
                'verbose_name_plural': 'songs',
                'verbose_name': 'song',
            },
        ),
        migrations.CreateModel(
            name='Rezonator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('image', models.FileField(blank=True, default='', null=True, upload_to='')),
                ('songs', models.ManyToManyField(to='rezonate.Song')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
